# Generated by Django 5.2.11 on 2026-03-05 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('campaigns', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vettingcampaign',
            name='appointment_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='approval_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='appointments.approvalstagetemplate'),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('ministerial', 'Ministerial'), ('judicial', 'Judicial'), ('board', 'Board / Commission'), ('local_gov', 'Local Government'), ('diplomatic', 'Diplomatic'), ('security', 'Security Services')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='gazette_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='jurisdiction',
            field=models.CharField(blank=True, choices=[('executive', 'Executive'), ('legislative', 'Legislative'), ('judicial', 'Judicial'), ('independent', 'Independent Body'), ('local', 'Local Government')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='appointment_exercises', to='positions.governmentposition'),
        ),
        migrations.AddField(
            model_name='vettingcampaign',
            name='requires_parliamentary_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='vettingcampaign',
            index=models.Index(fields=['exercise_type', 'jurisdiction'], name='campaigns_v_exercis_920994_idx'),
        ),
    ]
