# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointmentrecord_organization_and_more'),
        ('campaigns', '0002_vettingcampaign_appointment_authority_and_more'),
        ('tenants', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vettingcampaign',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetting_campaigns', to='tenants.organization'),
        ),
        migrations.AddIndex(
            model_name='vettingcampaign',
            index=models.Index(fields=['organization', 'status'], name='campaigns_v_organiz_cdf283_idx'),
        ),
    ]
