# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_backfill_campaign_organization"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vettingcampaign",
            name="campaigns_v_organiz_cdf283_idx",
        ),
        migrations.RemoveField(
            model_name="vettingcampaign",
            name="organization",
        ),
    ]
