# Generated by Django 5.2 on 2025-10-30 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_actions', '0001_initial'),
    ]

    # This migration has been adjusted to be a no-op because the initial
    # migration now creates the UUID primary key directly.
    operations = []
