# Generated by Django 6.0.2 on 2026-03-02 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('livekit_room_name', models.CharField(editable=False, max_length=128, unique=True)),
                ('allow_join_before_seconds', models.PositiveIntegerField(default=300)),
                ('reminder_before_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_start_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meetings', to='applications.vettingcase')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_video_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Meeting',
                'verbose_name_plural': 'Video Meetings',
                'ordering': ['scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoMeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('candidate', 'Candidate'), ('observer', 'Observer')], default='candidate', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('declined', 'Declined')], db_index=True, default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video_calls.videomeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Meeting Participant',
                'verbose_name_plural': 'Video Meeting Participants',
                'ordering': ['invited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videomeeting',
            index=models.Index(fields=['status', 'scheduled_start'], name='video_calls_status_9dcc15_idx'),
        ),
        migrations.AddIndex(
            model_name='videomeeting',
            index=models.Index(fields=['organizer', 'scheduled_start'], name='video_calls_organiz_ab8e85_idx'),
        ),
        migrations.AddIndex(
            model_name='videomeetingparticipant',
            index=models.Index(fields=['meeting', 'role'], name='video_calls_meeting_66d703_idx'),
        ),
        migrations.AddIndex(
            model_name='videomeetingparticipant',
            index=models.Index(fields=['user', 'status'], name='video_calls_user_id_37261d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videomeetingparticipant',
            unique_together={('meeting', 'user')},
        ),
    ]
