# Generated by Django 6.0.2 on 2026-03-02 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomeeting",
            name="reminder_before_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
    ]
