# Generated by Django 6.0.2 on 2026-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_calls", "0002_videomeeting_reminder_before_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomeeting",
            name="series_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
