# Generated by Django 6.0.2 on 2026-03-03 00:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0003_videomeeting_series_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMeetingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('rescheduled', 'Rescheduled'), ('extended', 'Extended'), ('cancelled', 'Cancelled'), ('started', 'Started'), ('completed', 'Completed'), ('left', 'Left')], max_length=32)),
                ('scope', models.CharField(choices=[('single', 'Single'), ('future', 'Future'), ('all', 'All')], default='single', max_length=12)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meeting_events', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='video_calls.videomeeting')),
            ],
            options={
                'verbose_name': 'Video Meeting Event',
                'verbose_name_plural': 'Video Meeting Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', 'created_at'], name='video_calls_meeting_540256_idx'), models.Index(fields=['action', 'created_at'], name='video_calls_action_c96fc9_idx')],
            },
        ),
    ]
