# Generated by Django 5.2.11 on 2026-03-04 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0004_videomeetingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videomeetingparticipant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='videomeetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='uq_video_meeting_participant_user'),
        ),
    ]
