# Generated by Django 5.2.11 on 2026-03-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0005_alter_videomeetingparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_before_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_before_last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_before_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
