# Generated by Django 5.2.11 on 2026-03-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0006_videomeeting_reminder_before_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_start_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_start_last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_start_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_time_up_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_time_up_last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_time_up_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='reminder_time_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
