# Generated by Django 5.2.11 on 2026-04-08 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0007_videomeeting_reminder_start_failure_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomeeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_video_meetings', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='videomeetingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meeting_events', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='videomeetingparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_meeting_participations', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
    ]
