# Generated by Django 5.2.11 on 2026-02-20 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAccessPass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pass_type', models.CharField(choices=[('portal', 'Portal Access'), ('results', 'Results Access')], db_index=True, default='portal', max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='issued', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, max_length=12)),
                ('max_uses', models.PositiveIntegerField(default=50)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_passes', to='candidates.candidateenrollment')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_passes', to='invitations.invitation')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_candidate_access_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAccessSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=255)),
                ('access_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='invitations.candidateaccesspass')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='candidates.candidateenrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidateaccesspass',
            index=models.Index(fields=['enrollment', 'pass_type', 'status'], name='invitations_enrollm_3d32e4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateaccesspass',
            index=models.Index(fields=['expires_at', 'status'], name='invitations_expires_a9a29f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateaccesssession',
            index=models.Index(fields=['session_key', 'status'], name='invitations_session_d76016_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateaccesssession',
            index=models.Index(fields=['enrollment', 'status'], name='invitations_enrollm_a1d2d6_idx'),
        ),
    ]
