# Generated by Django 5.2.8 on 2025-12-05 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModelMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=50)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("confusion_matrix", models.JSONField(default=dict)),
                ("trained_at", models.DateTimeField()),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_model_metrics",
                "ordering": ["-evaluated_at"],
            },
        ),
    ]
