# Generated by Django 5.2.11 on 2026-02-20 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], max_length=20)),
                ('category', models.CharField(choices=[('alert', 'Alert/Warning'), ('status_update', 'Status Update'), ('task_assignment', 'Task Assignment'), ('completion', 'Completion Notice'), ('reminder', 'Reminder')], max_length=30)),
                ('subject', models.CharField(help_text='Email subject or notification title', max_length=200)),
                ('body', models.TextField(help_text='Template body with {{variable}} placeholders')),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='Default CC recipients')),
                ('is_active', models.BooleanField(default=True)),
                ('variables_used', models.JSONField(default=list, help_text='List of variables used in template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('fraud_score_threshold', 'Fraud Score Above Threshold'), ('authenticity_score_threshold', 'Authenticity Score Below Threshold'), ('critical_flag_detected', 'Critical Flag Detected'), ('interview_red_flag', 'Interview Red Flag'), ('processing_error', 'Processing Error'), ('sla_breach', 'SLA Breach'), ('manual_review_required', 'Manual Review Required')], max_length=50)),
                ('threshold_value', models.FloatField(blank=True, help_text='Threshold value for score-based triggers', null=True)),
                ('additional_conditions', models.JSONField(default=dict, help_text='Additional conditions in JSON format')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='high', max_length=20)),
                ('cooldown_minutes', models.IntegerField(default=0, help_text='Minimum minutes between alerts for same case')),
                ('is_active', models.BooleanField(default=True)),
                ('times_triggered', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_users', models.ManyToManyField(help_text='Users to notify when rule triggers', related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('email_cc', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.vettingcase')),
                ('related_interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interviews.interviewsession')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['status', 'priority'], name='notificatio_status_e1eb7a_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
