# Generated by Django 5.2.7 on 2026-03-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_soft_archive'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_b9dbed_idx',
            old_name='notificatio_recipie_f7f57e_idx',
        ),
    ]
