# Generated by Django 5.2.11 on 2026-03-05 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStageAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('referred', 'Referred Back'), ('deferred', 'Deferred'), ('noted', 'Noted / Progressed')], max_length=20)),
                ('reason_note', models.TextField(blank=True)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('required_role', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('maps_to_status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominated_by_display', models.CharField(max_length=200)),
                ('nominated_by_org', models.CharField(blank=True, max_length=200)),
                ('nomination_date', models.DateField()),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('under_vetting', 'Under Vetting'), ('committee_review', 'Committee Review'), ('confirmation_pending', 'Awaiting Parliamentary Confirmation'), ('appointed', 'Appointed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('serving', 'Serving'), ('exited', 'Exited')], db_index=True, default='nominated', max_length=30)),
                ('committee_recommendation', models.TextField(blank=True)),
                ('final_decision_by_display', models.CharField(blank=True, max_length=200)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('gazette_number', models.CharField(blank=True, max_length=100)),
                ('gazette_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_records', to='campaigns.vettingcampaign')),
                ('final_decision_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_decisions', to=settings.AUTH_USER_MODEL)),
                ('nominated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
