# Generated by Django 5.2.11 on 2026-03-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecord',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_records', to='personnel.personnelrecord'),
        ),
    ]
