# Generated by Django 5.2.11 on 2026-03-05 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        ('appointments', '0002_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecord',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_records', to='positions.governmentposition'),
        ),
        migrations.AddField(
            model_name='appointmentrecord',
            name='vetting_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_records', to='applications.vettingcase'),
        ),
        migrations.AddField(
            model_name='appointmentstageaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentstageaction',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_actions', to='appointments.appointmentrecord'),
        ),
        migrations.AddField(
            model_name='appointmentstageaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.approvalstage'),
        ),
        migrations.AddField(
            model_name='approvalstagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_stage_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='appointments.approvalstagetemplate'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecord',
            index=models.Index(fields=['status', 'is_public'], name='appointment_status_9c7b75_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecord',
            index=models.Index(fields=['position', 'nominee'], name='appointment_positio_50bef1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecord',
            index=models.Index(fields=['nomination_date', 'status'], name='appointment_nominat_a3aef0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentstageaction',
            index=models.Index(fields=['appointment', 'acted_at'], name='appointment_appoint_01bf6b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstagetemplate',
            index=models.Index(fields=['exercise_type', 'name'], name='appointment_exercis_b71687_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstage',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='uniq_approval_stage_template_order'),
        ),
    ]
