# Generated by Django 5.2.11 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointmentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="serving"),
                fields=("position",),
                name="uniq_appt_serving_per_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status__in=[
                        "nominated",
                        "under_vetting",
                        "committee_review",
                        "confirmation_pending",
                        "appointed",
                        "serving",
                    ]
                ),
                fields=("position", "nominee"),
                name="uniq_appt_active_position_nominee",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(exit_date__isnull=True) | models.Q(status="exited"),
                name="chk_appt_exit_date_only_exited",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrecord",
            constraint=models.CheckConstraint(
                condition=~models.Q(status="exited") | models.Q(exit_date__isnull=False),
                name="chk_appt_exited_requires_exit_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrecord",
            constraint=models.CheckConstraint(
                condition=~models.Q(status__in=["serving", "exited"])
                | models.Q(appointment_date__isnull=False),
                name="chk_appt_serving_exited_need_appointment_date",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentrecord",
            index=models.Index(
                fields=["position", "status", "created_at"],
                name="idx_appt_pos_status_created",
            ),
        ),
    ]
