# Generated by Django 5.2.11 on 2026-03-06 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def bootstrap_appointment_publications(apps, schema_editor):
    AppointmentRecord = apps.get_model("appointments", "AppointmentRecord")
    AppointmentPublication = apps.get_model("appointments", "AppointmentPublication")
    db_alias = schema_editor.connection.alias

    existing_publication_ids = set(
        AppointmentPublication.objects.using(db_alias).values_list("appointment_id", flat=True)
    )

    rows_to_create = []
    for appointment in AppointmentRecord.objects.using(db_alias).all().iterator():
        if appointment.id in existing_publication_ids:
            continue

        is_published = bool(appointment.is_public)
        rows_to_create.append(
            AppointmentPublication(
                appointment_id=appointment.id,
                status="published" if is_published else "draft",
                publication_reference=appointment.gazette_number or "",
                publication_document_hash="",
                publication_notes="",
                published_by_id=(
                    (appointment.final_decision_by_user_id or appointment.nominated_by_user_id)
                    if is_published
                    else None
                ),
                published_at=appointment.updated_at if is_published else None,
                revoked_by_id=None,
                revoked_at=None,
                revocation_reason="",
            )
        )

    if rows_to_create:
        AppointmentPublication.objects.using(db_alias).bulk_create(rows_to_create, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_gams_integrity_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("revoked", "Revoked")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("publication_reference", models.CharField(blank=True, max_length=150)),
                ("publication_document_hash", models.CharField(blank=True, max_length=128)),
                ("publication_notes", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="appointments.appointmentrecord",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_appointment_records",
                        to=settings.AUTH_USER_MODEL,
                        db_constraint=False,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_appointment_records",
                        to=settings.AUTH_USER_MODEL,
                        db_constraint=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "published_at"], name="idx_apptpub_status_pubat"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=~models.Q(status="published") | models.Q(published_at__isnull=False),
                        name="chk_apptpub_pub_has_ts",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(status="revoked") | models.Q(revoked_at__isnull=False),
                        name="chk_apptpub_rev_has_ts",
                    ),
                ],
            },
        ),
        migrations.RunPython(bootstrap_appointment_publications, migrations.RunPython.noop),
    ]
