# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_vettingcase_organization_and_more'),
        ('appointments', '0005_appointmentpublication_lifecycle'),
        ('campaigns', '0002_vettingcampaign_appointment_authority_and_more'),
        ('governance', '0001_initial'),
        ('personnel', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_records', to='governance.organization'),
        ),
        migrations.AddField(
            model_name='approvalstagetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_templates', to='governance.organization'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecord',
            index=models.Index(fields=['organization', 'status'], name='idx_appt_org_status'),
        ),
        migrations.AddIndex(
            model_name='approvalstagetemplate',
            index=models.Index(fields=['organization', 'exercise_type'], name='appointment_organiz_98d54a_idx'),
        ),
    ]
