# Generated by Django 5.2.7 on 2026-03-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_appointment_committee_bindings(apps, schema_editor):
    AppointmentRecord = apps.get_model("appointments", "AppointmentRecord")
    AppointmentStageAction = apps.get_model("appointments", "AppointmentStageAction")
    ApprovalStage = apps.get_model("appointments", "ApprovalStage")
    CommitteeMembership = apps.get_model("governance", "CommitteeMembership")
    db_alias = schema_editor.connection.alias

    appointment_rows = []
    appointments = (
        AppointmentRecord.objects.using(db_alias)
        .filter(committee_id__isnull=True, appointment_exercise_id__isnull=False)
        .select_related("appointment_exercise", "appointment_exercise__approval_template")
        .order_by("created_at")
    )
    for appointment in appointments.iterator(chunk_size=200):
        exercise = getattr(appointment, "appointment_exercise", None)
        template_id = getattr(exercise, "approval_template_id", None)
        if not template_id:
            continue

        committee_ids = list(
            ApprovalStage.objects.using(db_alias)
            .filter(
                template_id=template_id,
                required_role__in=["committee_member", "committee_chair"],
                committee_id__isnull=False,
            )
            .values_list("committee_id", flat=True)
            .distinct()[:2]
        )
        if len(committee_ids) == 1:
            appointment.committee_id = committee_ids[0]
            appointment_rows.append(appointment)

    if appointment_rows:
        AppointmentRecord.objects.using(db_alias).bulk_update(appointment_rows, ["committee"], batch_size=500)

    action_rows = []
    actions = (
        AppointmentStageAction.objects.using(db_alias)
        .filter(committee_membership_id__isnull=True, stage_id__isnull=False, stage__committee_id__isnull=False)
        .select_related("stage")
        .order_by("acted_at")
    )
    for action in actions.iterator(chunk_size=200):
        membership = (
            CommitteeMembership.objects.using(db_alias)
            .filter(
                user_id=action.actor_id,
                committee_id=action.stage.committee_id,
            )
            .order_by("-is_active", "created_at")
            .first()
        )
        if membership is None:
            continue
        action.committee_membership_id = membership.id
        action_rows.append(action)

    if action_rows:
        AppointmentStageAction.objects.using(db_alias).bulk_update(
            action_rows,
            ["committee_membership"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_backfill_vettingcase_organization'),
        ('appointments', '0007_backfill_appointment_organization'),
        ('campaigns', '0004_backfill_campaign_organization'),
        ('governance', '0001_initial'),
        ('personnel', '0002_personnelrecord_organization_and_more'),
        ('positions', '0002_governmentposition_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecord',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_records', to='governance.committee'),
        ),
        migrations.AddField(
            model_name='appointmentstageaction',
            name='committee_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_stage_actions', to='governance.committeemembership'),
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stages', to='governance.committee'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecord',
            index=models.Index(fields=['committee', 'status'], name='idx_appt_committee_status'),
        ),
        migrations.AddIndex(
            model_name='appointmentstageaction',
            index=models.Index(fields=['committee_membership', 'acted_at'], name='appointment_committ_faf23e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstage',
            index=models.Index(fields=['template', 'committee'], name='appointment_templat_39992d_idx'),
        ),
        migrations.RunPython(backfill_appointment_committee_bindings, migrations.RunPython.noop),
    ]
