# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_appointmentrecord_committee_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointmentrecord",
            name="idx_appt_org_status",
        ),
        migrations.RemoveIndex(
            model_name="approvalstagetemplate",
            name="appointment_organiz_98d54a_idx",
        ),
        migrations.RemoveField(
            model_name="appointmentrecord",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="approvalstagetemplate",
            name="organization",
        ),
    ]
