# Generated by Django 5.2.11 on 2026-05-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_committeevote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='committeevote',
            new_name='appointment_appoint_08ccd8_idx',
            old_name='appt_committeevote_appt_stage_idx',
        ),
    ]
