# Generated by Django 6.0.2 on 2026-02-17 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('general', 'General Background'), ('education', 'Educational Background'), ('employment', 'Employment History'), ('verification', 'Document Verification'), ('flag_specific', 'Flag-Specific Clarification'), ('behavioral', 'Behavioral Assessment'), ('situational', 'Situational Question')], db_index=True, max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('targets_flag_type', models.CharField(blank=True, help_text='Which type of flag this question addresses', max_length=50)),
                ('evaluation_rubric', models.TextField(help_text='Criteria for evaluating responses to this question')),
                ('expected_keywords', models.JSONField(default=list, help_text='Keywords/phrases expected in good answers')),
                ('times_used', models.IntegerField(default=0)),
                ('average_response_quality', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['question_type', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('use_dynamic_questions', models.BooleanField(default=True, help_text='Generate questions based on flags vs. use predefined set')),
                ('max_questions', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('current_question_number', models.IntegerField(default=0)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('communication_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interview_summary', models.TextField(blank=True)),
                ('key_findings', models.JSONField(default=list)),
                ('red_flags_detected', models.JSONField(default=list)),
                ('flags_resolved_count', models.IntegerField(default=0)),
                ('flags_unresolved_count', models.IntegerField(default=0)),
                ('conversation_history', models.JSONField(default=list, help_text='Full Q&A history for context building')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='applications.vettingcase')),
                ('flags_addressed', models.ManyToManyField(blank=True, related_name='addressed_in_sessions', to='applications.interrogationflag')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Order in the interview')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interview_videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL if stored externally (S3)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interview_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('transcript_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sentiment', models.CharField(blank=True, help_text='Overall emotional sentiment', max_length=50)),
                ('sentiment_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_quality_score', models.FloatField(blank=True, help_text='Overall response quality from LLM evaluation', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('relevance_score', models.FloatField(blank=True, help_text='How relevant the answer is to the question', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completeness_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coherence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('llm_evaluation', models.JSONField(default=dict, help_text='Detailed evaluation from LLM (GPT-4/Claude)')),
                ('key_points_extracted', models.JSONField(default=list, help_text='Main points from the response')),
                ('concerns_detected', models.JSONField(default=list, help_text='Any concerns or red flags in the response')),
                ('response_duration_seconds', models.IntegerField(default=0, help_text='How long the candidate spoke')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewquestion')),
                ('target_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_responses', to='applications.interrogationflag')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Response',
                'verbose_name_plural': 'Interview Responses',
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Overall rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('clarity_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('consistency_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('general_comments', models.TextField()),
                ('recommendation', models.CharField(choices=[('strongly_approve', 'Strongly Approve'), ('approve', 'Approve'), ('neutral', 'Neutral'), ('reject', 'Reject'), ('strongly_reject', 'Strongly Reject')], max_length=20)),
                ('decision_rationale', models.TextField()),
                ('agrees_with_ai', models.BooleanField(help_text='Does reviewer agree with AI evaluation?')),
                ('ai_override_reason', models.TextField(blank=True, help_text='If disagreeing with AI, explain why')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Feedback',
                'verbose_name_plural': 'Interview Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detected', models.BooleanField(default=False)),
                ('face_detection_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('eye_contact_percentage', models.FloatField(blank=True, help_text='Approximate percentage of time looking at camera', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gaze_direction_changes', models.IntegerField(default=0, help_text='Number of times gaze direction changed')),
                ('dominant_emotion', models.CharField(blank=True, help_text='Most common emotion detected', max_length=50)),
                ('emotion_distribution', models.JSONField(default=dict, help_text='Distribution of emotions throughout response')),
                ('confidence_level', models.FloatField(blank=True, help_text='Overall confidence based on visual cues', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stress_level', models.FloatField(blank=True, help_text='Estimated stress level', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('head_movement_count', models.IntegerField(default=0, help_text='Significant head movements')),
                ('fidgeting_detected', models.BooleanField(default=False)),
                ('behavioral_indicators', models.JSONField(default=list, help_text='List of observed behavioral patterns')),
                ('raw_analysis_data', models.JSONField(default=dict, help_text='Complete raw analysis from CV models')),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('analysis_duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_analysis', to='interviews.interviewresponse')),
            ],
            options={
                'verbose_name': 'Video Analysis',
                'verbose_name_plural': 'Video Analyses',
            },
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['question_type', 'is_active'], name='interviews__questio_fac9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['difficulty'], name='interviews__difficu_4c08ef_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['session_id', 'status'], name='interviews__session_4fa65c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['case', 'status'], name='interviews__case_id_319164_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['-created_at'], name='interviews__created_4d758c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewresponse',
            index=models.Index(fields=['session', 'sequence_number'], name='interviews__session_98e62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together={('session', 'sequence_number')},
        ),
    ]
