# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="loginhistory",
            new_name="users_login_user_id_b625c3_idx",
            old_name="users_loginhistory_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="users_passw_user_id_4a6c7a_idx",
            old_name="users_passwordresettoken_user_token_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_email_9f87be_idx",
            old_name="users_user_email_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_created_cf865c_idx",
            old_name="users_user_created_at_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
