# Generated by Django 6.0.2 on 2026-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_organizationmembership_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmembership",
            name="organization",
        ),
    ]
