# Generated by Django 5.2.8 on 2026-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
