# Generated by Django 5.2.7 on 2026-03-08 18:08

from django.conf import settings
from django.db import migrations, models


def backfill_scope_context_from_changes(apps, schema_editor):
    AuditLog = apps.get_model("audit", "AuditLog")
    batch = []
    queryset = AuditLog.objects.filter(scope_organization_id="", scope_committee_id="")

    for row in queryset.iterator(chunk_size=1000):
        changes = row.changes if isinstance(row.changes, dict) else {}
        organization_id = str(changes.get("organization_id") or "").strip()
        committee_id = str(changes.get("committee_id") or "").strip()
        if not organization_id and not committee_id:
            continue
        row.scope_organization_id = organization_id
        row.scope_committee_id = committee_id
        batch.append(row)
        if len(batch) >= 1000:
            AuditLog.objects.bulk_update(batch, ["scope_organization_id", "scope_committee_id"])
            batch.clear()

    if batch:
        AuditLog.objects.bulk_update(batch, ["scope_organization_id", "scope_committee_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_gams_scope_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='scope_committee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='scope_organization_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(backfill_scope_context_from_changes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['scope_organization_id', 'created_at'], name='audit_logs_scope_o_a0b0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['scope_committee_id', 'created_at'], name='audit_logs_scope_c_8a33da_idx'),
        ),
    ]
