# Generated by Django 5.2.11 on 2026-03-01 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('sandbox', 'Sandbox')], default='stripe', max_length=32)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='open', max_length=32)),
                ('payment_status', models.CharField(blank=True, default='', max_length=64)),
                ('plan_id', models.CharField(max_length=64)),
                ('plan_name', models.CharField(max_length=128)),
                ('billing_cycle', models.CharField(max_length=16)),
                ('payment_method', models.CharField(default='card', max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_last_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('signature', models.TextField(blank=True, default='')),
                ('livemode', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
