# Generated by Django 5.2.11 on 2026-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsubscription',
            name='registration_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='registration_consumed_by_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
