# Generated by Django 5.2.11 on 2026-03-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _normalize_email(value):
    return str(value or "").strip().lower()


def _resolved_membership_org_id(*, memberships):
    default_membership = memberships.filter(is_default=True).first()
    if default_membership is not None and getattr(default_membership, "organization_id", None):
        return str(default_membership.organization_id)

    org_ids = []
    for org_id in memberships.values_list("organization_id", flat=True):
        normalized = str(org_id or "").strip()
        if not normalized or normalized in org_ids:
            continue
        org_ids.append(normalized)

    if len(org_ids) == 1:
        return org_ids[0]
    return None


def backfill_subscription_organization(apps, schema_editor):
    BillingSubscription = apps.get_model("billing", "BillingSubscription")
    Organization = apps.get_model("governance", "Organization")
    OrganizationMembership = apps.get_model("governance", "OrganizationMembership")
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(auth_app_label, auth_model_name)
    db_alias = schema_editor.connection.alias

    known_organization_ids = {
        str(org_id)
        for org_id in Organization.objects.using(db_alias).values_list("id", flat=True)
        if org_id
    }
    email_org_cache: dict[str, str | None] = {}

    def resolve_org_from_email(email_value: str) -> str | None:
        normalized_email = _normalize_email(email_value)
        if not normalized_email:
            return None
        if normalized_email in email_org_cache:
            return email_org_cache[normalized_email]

        user = (
            User.objects.using(db_alias)
            .filter(email__iexact=normalized_email)
            .order_by("id")
            .first()
        )
        if user is None:
            email_org_cache[normalized_email] = None
            return None

        memberships = (
            OrganizationMembership.objects.using(db_alias)
            .filter(user_id=user.id, is_active=True)
            .order_by("-is_default", "created_at")
        )
        resolved_org_id = _resolved_membership_org_id(memberships=memberships)
        email_org_cache[normalized_email] = resolved_org_id
        return resolved_org_id

    subscriptions = (
        BillingSubscription.objects.using(db_alias)
        .filter(organization_id__isnull=True)
        .order_by("created_at")
    )
    rows_to_update = []

    for subscription in subscriptions.iterator(chunk_size=500):
        metadata = subscription.metadata if isinstance(subscription.metadata, dict) else {}
        resolved_ids: list[str] = []

        metadata_org_id = str(metadata.get("organization_id") or "").strip()
        if metadata_org_id and metadata_org_id in known_organization_ids:
            resolved_ids.append(metadata_org_id)

        registration_org_id = resolve_org_from_email(getattr(subscription, "registration_consumed_by_email", ""))
        if registration_org_id:
            resolved_ids.append(registration_org_id)

        workspace_org_id = resolve_org_from_email(metadata.get("workspace_email"))
        if workspace_org_id:
            resolved_ids.append(workspace_org_id)

        unique_resolved_ids: list[str] = []
        for resolved_id in resolved_ids:
            if resolved_id not in unique_resolved_ids:
                unique_resolved_ids.append(resolved_id)

        if len(unique_resolved_ids) != 1:
            continue

        subscription.organization_id = unique_resolved_ids[0]
        rows_to_update.append(subscription)

    if rows_to_update:
        BillingSubscription.objects.using(db_alias).bulk_update(
            rows_to_update,
            ["organization"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0003_billingsubscription_add_paystack_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsubscription",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_subscriptions",
                to="governance.organization",
            ),
        ),
        migrations.RunPython(backfill_subscription_organization, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="billingsubscription",
            index=models.Index(
                fields=["organization", "status", "payment_status"],
                name="billing_bil_organiz_8d35d4_idx",
            ),
        ),
    ]
