# Generated by Django 5.2.11 on 2026-03-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0004_billingsubscription_organization_and_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationOnboardingToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_hash", models.CharField(db_index=True, max_length=128, unique=True)),
                ("token_prefix", models.CharField(blank=True, db_index=True, default="", max_length=24)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("allowed_email_domain", models.CharField(blank=True, default="", max_length=255)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organization_onboarding_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_tokens",
                        to="governance.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_tokens",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="organizationonboardingtoken",
            index=models.Index(fields=["organization", "is_active"], name="bill_onboard_org_active_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationonboardingtoken",
            index=models.Index(fields=["organization", "expires_at"], name="bill_onboard_org_expires_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationonboardingtoken",
            index=models.Index(fields=["subscription", "is_active"], name="bill_onboard_sub_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizationonboardingtoken",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("organization",),
                name="uniq_org_onboarding_token_active_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationonboardingtoken",
            constraint=models.CheckConstraint(
                condition=Q(max_uses__isnull=True) | Q(max_uses__gt=0),
                name="chk_org_onboarding_token_max_uses_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationonboardingtoken",
            constraint=models.CheckConstraint(
                condition=Q(uses__gte=0),
                name="chk_org_onboarding_token_uses_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationonboardingtoken",
            constraint=models.CheckConstraint(
                condition=Q(revoked_at__isnull=True) | Q(is_active=False),
                name="chk_org_onboarding_token_revoked_inactive",
            ),
        ),
    ]
