# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_organizationonboardingtoken"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationonboardingtoken",
            name="uniq_org_onboarding_token_active_org",
        ),
        migrations.RemoveIndex(
            model_name="billingsubscription",
            name="billing_bil_organiz_8d35d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="organizationonboardingtoken",
            name="bill_onboard_org_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="organizationonboardingtoken",
            name="bill_onboard_org_expires_idx",
        ),
        # NOTE: BillingSubscription.organization FK is intentionally kept.
        # It is nullable and used for per-org subscription filtering in services
        # and tests (which share a single test schema and cannot rely on
        # schema-level isolation alone).
        migrations.RemoveField(
            model_name="organizationonboardingtoken",
            name="organization",
        ),
    ]
