# Generated by Django 6.0.2 on 2026-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0006_remove_organizationonboardingtoken_uniq_org_onboarding_token_active_org_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingsubscription",
            name="organization",
        ),
    ]
