# Generated by Django 5.2.11 on 2026-02-20 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('github', 'GitHub')], default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Slug Field')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='authentication.userprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'indexes': [models.Index(fields=['user', 'token'], name='authenticat_user_id_28fe79_idx')],
            },
        ),
    ]
