# Generated by Django 5.2.11 on 2026-02-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_registration_method_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
    ]
