# Generated by Django 6.0.2 on 2026-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_two_factor_backup_codes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="passwordresettoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("admin_user__isnull", True), ("user__isnull", False)),
                    models.Q(("admin_user__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="chk_password_reset_token_one_user",
            ),
        ),
    ]
