# Generated by Django 5.2.11 on 2026-03-05 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_candidatesocialprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Ghanaian', max_length=100)),
                ('national_id_hash', models.CharField(blank=True, max_length=128)),
                ('national_id_encrypted', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('bio_summary', models.TextField(blank=True)),
                ('academic_qualifications', models.JSONField(blank=True, default=list)),
                ('professional_history', models.JSONField(blank=True, default=list)),
                ('is_active_officeholder', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_record', to='candidates.candidate')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_active_officeholder', 'is_public'], name='personnel_p_is_acti_0ae53e_idx')],
            },
        ),
    ]
