# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidatesocialprofile'),
        ('governance', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_records', to='governance.organization'),
        ),
        migrations.AddIndex(
            model_name='personnelrecord',
            index=models.Index(fields=['organization', 'is_active_officeholder'], name='personnel_p_organiz_a2e9f8_idx'),
        ),
    ]
