# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_personnelrecord_organization_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personnelrecord",
            name="personnel_p_organiz_a2e9f8_idx",
        ),
        migrations.RemoveField(
            model_name="personnelrecord",
            name="organization",
        ),
    ]
