# Generated by Django 6.0.2 on 2026-02-17 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria_type', models.CharField(choices=[('document', 'Document Quality'), ('consistency', 'Data Consistency'), ('interview', 'Interview Performance'), ('behavioral', 'Behavioral Assessment'), ('technical', 'Technical Competency'), ('custom', 'Custom Criterion')], max_length=20)),
                ('scoring_method', models.CharField(choices=[('ai_score', 'AI-Generated Score'), ('manual_rating', 'Manual Rating'), ('binary', 'Pass/Fail'), ('calculated', 'Calculated from Sub-Criteria')], default='ai_score', max_length=20)),
                ('weight', models.IntegerField(help_text='Weight within parent rubric or category', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_score', models.IntegerField(blank=True, help_text='Minimum required score for this criterion', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mandatory', models.BooleanField(default=False, help_text='Must pass this criterion to pass overall')),
                ('evaluation_guidelines', models.TextField(blank=True, help_text='Instructions for manual evaluation')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['rubric', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RubricEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('requires_review', 'Requires Manual Review')], default='pending', max_length=20)),
                ('document_authenticity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fraud_risk_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interview_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manual_review_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_document_score', models.FloatField(blank=True, null=True)),
                ('weighted_consistency_score', models.FloatField(blank=True, null=True)),
                ('weighted_fraud_score', models.FloatField(blank=True, null=True)),
                ('weighted_interview_score', models.FloatField(blank=True, null=True)),
                ('weighted_manual_score', models.FloatField(blank=True, null=True)),
                ('total_weighted_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passes_threshold', models.BooleanField(null=True)),
                ('final_decision', models.CharField(choices=[('auto_approved', 'Automatically Approved'), ('auto_rejected', 'Automatically Rejected'), ('manual_approved', 'Manually Approved'), ('manual_rejected', 'Manually Rejected'), ('pending', 'Pending Decision')], default='pending', max_length=20)),
                ('critical_flags_present', models.BooleanField(default=False)),
                ('unresolved_flags_count', models.IntegerField(default=0)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_reasons', models.JSONField(default=list, help_text='Reasons requiring manual review')),
                ('criterion_scores', models.JSONField(default=dict, help_text='Individual criterion scores')),
                ('evaluation_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluation', to='applications.vettingcase')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Rubric Evaluation',
                'verbose_name_plural': 'Rubric Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriteriaOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overridden_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('justification', models.TextField(help_text='Explanation for the override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='rubrics.rubriccriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='rubrics.rubricevaluation')),
            ],
            options={
                'verbose_name': 'Criteria Override',
                'verbose_name_plural': 'Criteria Overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VettingRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rubric_type', models.CharField(choices=[('general', 'General Purpose'), ('technical', 'Technical Position'), ('executive', 'Executive Level'), ('sensitive', 'High-Security Position'), ('custom', 'Custom')], default='general', max_length=20)),
                ('document_authenticity_weight', models.IntegerField(default=25, help_text='Weight for document authenticity (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_weight', models.IntegerField(default=20, help_text='Weight for cross-document consistency', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fraud_detection_weight', models.IntegerField(default=20, help_text='Weight for fraud risk assessment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interview_weight', models.IntegerField(default=25, help_text='Weight for interview performance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manual_review_weight', models.IntegerField(default=10, help_text='Weight for manual reviewer assessment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score to pass vetting', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_approve_threshold', models.IntegerField(default=90, help_text='Score for automatic approval without review', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_reject_threshold', models.IntegerField(default=40, help_text='Score for automatic rejection', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_document_score', models.IntegerField(default=60, help_text='Minimum acceptable document authenticity score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_fraud_score', models.IntegerField(default=50, help_text='Maximum acceptable fraud risk score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('require_interview', models.BooleanField(default=True, help_text='Is interview mandatory?')),
                ('critical_flags_auto_fail', models.BooleanField(default=True, help_text='Automatically fail if critical flags detected')),
                ('max_unresolved_flags', models.IntegerField(default=2, help_text='Maximum unresolved flags before manual review required')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Vetting Rubric',
                'verbose_name_plural': 'Vetting Rubrics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='rubrics.vettingrubric'),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.vettingrubric'),
        ),
        migrations.AddIndex(
            model_name='vettingrubric',
            index=models.Index(fields=['is_active', 'is_default'], name='rubrics_vet_is_acti_b8a33e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubriccriteria',
            unique_together={('rubric', 'name')},
        ),
    ]
