# Generated by Django 6.0.2 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VettingDecisionRecommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "recommendation_status",
                    models.CharField(
                        choices=[
                            ("recommend_approve", "Recommend Approve"),
                            ("recommend_reject", "Recommend Reject"),
                            ("recommend_manual_review", "Recommend Manual Review"),
                        ],
                        db_index=True,
                        default="recommend_manual_review",
                        max_length=30,
                    ),
                ),
                ("blocking_issues", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("decision_basis", models.JSONField(blank=True, default=dict)),
                ("explanation", models.JSONField(blank=True, default=dict)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                ("ai_signal_snapshot", models.JSONField(blank=True, default=dict)),
                ("advisory_only", models.BooleanField(default=True)),
                ("engine_version", models.CharField(default="v1", max_length=20)),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_recommendations",
                        to="applications.vettingcase",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_vetting_decision_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubric_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_recommendations",
                        to="rubrics.rubricevaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vetting Decision Recommendation",
                "verbose_name_plural": "Vetting Decision Recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VettingDecisionOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("previous_recommendation_status", models.CharField(max_length=30)),
                (
                    "overridden_recommendation_status",
                    models.CharField(
                        choices=[
                            ("recommend_approve", "Recommend Approve"),
                            ("recommend_reject", "Recommend Reject"),
                            ("recommend_manual_review", "Recommend Manual Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rationale", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vetting_decision_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="rubrics.vettingdecisionrecommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vetting Decision Override",
                "verbose_name_plural": "Vetting Decision Overrides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="vettingdecisionrecommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("case",),
                name="uniq_vetting_decision_latest_per_case",
            ),
        ),
        migrations.AddIndex(
            model_name="vettingdecisionrecommendation",
            index=models.Index(fields=["case", "is_latest"], name="idx_vdr_case_latest"),
        ),
        migrations.AddIndex(
            model_name="vettingdecisionrecommendation",
            index=models.Index(
                fields=["rubric_evaluation", "is_latest"],
                name="idx_vdr_eval_latest",
            ),
        ),
        migrations.AddIndex(
            model_name="vettingdecisionrecommendation",
            index=models.Index(
                fields=["recommendation_status", "created_at"],
                name="idx_vdr_status_created",
            ),
        ),
        migrations.AddIndex(
            model_name="vettingdecisionoverride",
            index=models.Index(
                fields=["recommendation", "created_at"],
                name="idx_vdo_rec_created",
            ),
        ),
    ]
