# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        ('rubrics', '0002_vetting_decision_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vettingrubric',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetting_rubrics', to='governance.organization'),
        ),
        migrations.AddIndex(
            model_name='vettingrubric',
            index=models.Index(fields=['organization', 'is_active'], name='rubrics_vet_organiz_f5fcd7_idx'),
        ),
    ]
