# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0003_vettingrubric_organization_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vettingrubric",
            name="rubrics_vet_organiz_f5fcd7_idx",
        ),
        migrations.RemoveField(
            model_name="vettingrubric",
            name="organization",
        ),
    ]
