# Generated by Django 5.2.11 on 2026-04-08 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_remove_vettingrubric_rubrics_vet_organiz_f5fcd7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaoverride',
            name='overridden_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='rubricevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='vettingdecisionoverride',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetting_decision_overrides', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='vettingdecisionrecommendation',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_vetting_decision_recommendations', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='vettingrubric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
    ]
