# Generated by Django 5.2.11 on 2026-02-27 13:26

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSocialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('x', 'X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('other', 'Other')], db_index=True, max_length=20)),
                ('url', models.URLField(blank=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='candidates.candidate')),
            ],
            options={
                'ordering': ['candidate_id', 'platform', '-created_at'],
                'indexes': [models.Index(fields=['candidate', 'platform'], name='candidates__candida_3a7bea_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'platform', 'url', 'username'), name='uniq_candidate_social_profile')],
            },
        ),
    ]
