# Generated by Django 6.0.2 on 2026-02-17 01:03

import apps.applications.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('birth_certificate', 'Birth Certificate'), ('degree', 'Educational Degree/Certificate'), ('transcript', 'Academic Transcript'), ('employment_letter', 'Employment Letter'), ('reference_letter', 'Reference Letter'), ('pay_slip', 'Pay Slip'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('other', 'Other')], db_index=True, max_length=50)),
                ('file', models.FileField(upload_to=apps.applications.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued for Processing'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('flagged', 'Flagged for Review')], db_index=True, default='uploaded', max_length=20)),
                ('ocr_completed', models.BooleanField(default=False)),
                ('authenticity_check_completed', models.BooleanField(default=False)),
                ('fraud_check_completed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted from document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['case', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsistencyCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text="Field being checked (e.g., 'name', 'date_of_birth')", max_length=100)),
                ('is_consistent', models.BooleanField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('discrepancy_description', models.TextField()),
                ('conflicting_values', models.JSONField(default=list, help_text='List of conflicting values found')),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_checks', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('documents_compared', models.ManyToManyField(related_name='consistency_checks', to='applications.document')),
            ],
            options={
                'verbose_name': 'Consistency Check',
                'verbose_name_plural': 'Consistency Checks',
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ocr_language', models.CharField(default='en', max_length=10)),
                ('authenticity_score', models.FloatField(help_text='Likelihood document is authentic (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('authenticity_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_authentic', models.BooleanField()),
                ('metadata_check_passed', models.BooleanField(default=False)),
                ('visual_check_passed', models.BooleanField(default=False)),
                ('tampering_detected', models.BooleanField(default=False)),
                ('fraud_risk_score', models.FloatField(help_text='Probability of fraud (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fraud_prediction', models.CharField(choices=[('legitimate', 'Legitimate'), ('suspicious', 'Suspicious'), ('fraudulent', 'Fraudulent')], max_length=20)),
                ('fraud_indicators', models.JSONField(default=list, help_text='List of detected fraud indicators')),
                ('detailed_results', models.JSONField(default=dict, help_text='Complete analysis results from AI models')),
                ('ocr_model_version', models.CharField(blank=True, max_length=50)),
                ('authenticity_model_version', models.CharField(blank=True, max_length=50)),
                ('fraud_model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Time taken for analysis', null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='applications.document')),
            ],
            options={
                'verbose_name': 'Verification Result',
                'verbose_name_plural': 'Verification Results',
            },
        ),
        migrations.CreateModel(
            name='VettingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('position_applied', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('document_upload', 'Document Upload'), ('document_analysis', 'Document Analysis'), ('interview_scheduled', 'Interview Scheduled'), ('interview_in_progress', 'Interview In Progress'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('overall_score', models.FloatField(blank=True, help_text='Overall vetting score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('document_authenticity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fraud_risk_score', models.FloatField(blank=True, help_text='Higher score = higher fraud risk', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interview_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('red_flags_count', models.IntegerField(default=0)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('internal_comments', models.TextField(blank=True)),
                ('documents_uploaded', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('interview_completed', models.BooleanField(default=False)),
                ('final_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('decision_rationale', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_completion_date', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='vetting_cases', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['internal', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cases', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Vetting Case',
                'verbose_name_plural': 'Vetting Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterrogationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('consistency_mismatch', 'Consistency Mismatch'), ('missing_information', 'Missing Information'), ('suspicious_document', 'Suspicious Document'), ('timeline_conflict', 'Timeline Conflict'), ('credential_issue', 'Credential Issue'), ('employment_gap', 'Employment Gap'), ('reference_discrepancy', 'Reference Discrepancy'), ('authenticity_concern', 'Authenticity Concern'), ('fraud_indicator', 'Fraud Indicator'), ('other', 'Other')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('addressed', 'Addressed in Interview'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('data_point', models.CharField(blank=True, help_text='Specific data point causing the flag', max_length=200)),
                ('evidence', models.JSONField(default=dict, help_text='Supporting evidence for the flag')),
                ('suggested_questions', models.JSONField(default=list, help_text='Suggested interview questions to address this flag')),
                ('resolution_summary', models.TextField(blank=True)),
                ('resolution_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_consistency_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_flags', to='applications.consistencycheck')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='flags', to='applications.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_flags', to='applications.vettingcase')),
            ],
            options={
                'verbose_name': 'Interrogation Flag',
                'verbose_name_plural': 'Interrogation Flags',
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.vettingcase'),
        ),
        migrations.AddField(
            model_name='consistencycheck',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_checks', to='applications.vettingcase'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['case_id', 'status'], name='application_case_id_2fc24d_idx'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_325a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['assigned_to', 'status'], name='application_assigne_02d8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['-created_at'], name='application_created_b32b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['status', 'priority'], name='application_status_495362_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogationflag',
            index=models.Index(fields=['case', 'status'], name='application_case_id_709fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogationflag',
            index=models.Index(fields=['severity', 'status'], name='application_severit_8887cd_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogationflag',
            index=models.Index(fields=['flag_type'], name='application_flag_ty_9567e1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case', 'document_type'], name='application_case_id_3d60d5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='application_status_2b92d8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='application_uploade_5ebc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='consistencycheck',
            index=models.Index(fields=['case', 'is_consistent'], name='application_case_id_f0f326_idx'),
        ),
        migrations.AddIndex(
            model_name='consistencycheck',
            index=models.Index(fields=['severity'], name='application_severit_5c71b8_idx'),
        ),
    ]
