# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        ('candidates', '0002_candidatesocialprofile'),
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vettingcase',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetting_cases', to='governance.organization'),
        ),
        migrations.AddIndex(
            model_name='vettingcase',
            index=models.Index(fields=['organization', 'status'], name='application_organiz_9b0559_idx'),
        ),
    ]
