# Generated by Django 5.2.7 on 2026-03-09 21:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_backfill_vettingcase_organization'),
        ('governance', '0002_committee_active_chair_constraint'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source_category', models.CharField(choices=[('national_identity', 'National Identity Registry'), ('civil_service', 'Civil Service / Employment Registry'), ('academic_credentials', 'Academic Credential Registry'), ('sanctions', 'Sanctions / Disciplinary Registry'), ('prior_appointments', 'Prior Appointment Registry'), ('organization_legitimacy', 'Organization Legitimacy Registry'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('integration_mode', models.CharField(choices=[('manual', 'Manual Upload / Officer Entry'), ('mock', 'Mock Provider'), ('api', 'API Integration'), ('batch', 'Batch Import')], default='manual', max_length=20)),
                ('advisory_only', models.BooleanField(default=True, help_text='External source outputs remain advisory evidence and never final authority.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verification_sources', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sources', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Verification Source',
                'verbose_name_plural': 'Verification Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('unavailable', 'Unavailable'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('purpose', models.CharField(blank=True, default='vetting_evidence', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('subject_identifiers', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='applications.vettingcase')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='tenants.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='applications.verificationsource')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalVerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_status', models.CharField(choices=[('verified', 'Verified'), ('mismatch', 'Mismatch'), ('not_found', 'Not Found'), ('inconclusive', 'Inconclusive'), ('error', 'Error'), ('unavailable', 'Unavailable')], db_index=True, max_length=20)),
                ('recommendation', models.CharField(choices=[('clear', 'Clear'), ('review', 'Manual Review'), ('escalate', 'Escalate'), ('reject', 'Reject'), ('unavailable', 'Unavailable')], default='review', help_text='Advisory recommendation only; final decision remains human.', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('advisory_flags', models.JSONField(blank=True, default=list)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('normalized_evidence', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload_redacted', models.BooleanField(default=True, help_text='True when payload is already redacted/sanitized for internal storage.')),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_verification_results', to='applications.vettingcase')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_verification_results', to='tenants.organization')),
                ('verification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_result', to='applications.verificationrequest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_verification_results', to='applications.verificationsource')),
            ],
            options={
                'verbose_name': 'External Verification Result',
                'verbose_name_plural': 'External Verification Results',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationsource',
            index=models.Index(fields=['organization', 'is_active'], name='application_organiz_607675_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsource',
            index=models.Index(fields=['source_category', 'is_active'], name='application_source__5eafb0_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['case', 'status'], name='application_case_id_ef930f_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['source', 'status'], name='application_source__7620a1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['organization', 'status'], name='application_organiz_2b7eab_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('case', 'source', 'idempotency_key'), name='uniq_verif_req_case_source_idempotency'),
        ),
        migrations.AddIndex(
            model_name='externalverificationresult',
            index=models.Index(fields=['case', 'result_status'], name='application_case_id_23d874_idx'),
        ),
        migrations.AddIndex(
            model_name='externalverificationresult',
            index=models.Index(fields=['source', 'result_status'], name='application_source__660cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='externalverificationresult',
            index=models.Index(fields=['organization', 'result_status'], name='application_organiz_e67675_idx'),
        ),
    ]
