# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0006_interrogation_flag_unique_constraint_and_verification_result_clean",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externalverificationresult",
            name="application_organiz_e67675_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationrequest",
            name="application_organiz_2b7eab_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationsource",
            name="application_organiz_607675_idx",
        ),
        migrations.RemoveIndex(
            model_name="vettingcase",
            name="application_organiz_9b0559_idx",
        ),
        migrations.RemoveField(
            model_name="externalverificationresult",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="verificationrequest",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="verificationsource",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="vettingcase",
            name="organization",
        ),
    ]
