# Generated by Django 6.0.2 on 2026-05-06 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_cross_schema_fk_no_db_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vettingcase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('document_upload', 'Document Upload'), ('document_analysis', 'Document Analysis'), ('interview_scheduled', 'Interview Scheduled'), ('interview_in_progress', 'Interview In Progress'), ('under_review', 'Under Review'), ('info_requested', 'Information Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='CaseInfoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Description of what additional information is needed')),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to='applications.vettingcase')),
                ('requested_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_info_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Info Request',
                'verbose_name_plural': 'Case Info Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='application_case_id_ff7fac_idx')],
            },
        ),
    ]
