# Generated by Django 5.2.11 on 2026-02-27 16:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('criminal', 'Criminal Records'), ('employment', 'Employment History'), ('education', 'Education Verification'), ('kyc_aml', 'KYC/AML'), ('identity', 'Identity Verification')], db_index=True, max_length=30)),
                ('provider_key', models.CharField(db_index=True, default='mock', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('manual_review', 'Manual Review'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('score', models.FloatField(blank=True, help_text='Normalized provider score (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('recommendation', models.CharField(choices=[('clear', 'Clear'), ('review', 'Manual Review'), ('reject', 'Reject'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('consent_evidence', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='applications.vettingcase')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_background_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundCheckEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('provider_update', 'Provider Update'), ('webhook', 'Webhook'), ('manual', 'Manual Update'), ('error', 'Error')], max_length=30)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='background_checks.backgroundcheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundcheck',
            index=models.Index(fields=['case', 'status'], name='background__case_id_707863_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundcheck',
            index=models.Index(fields=['check_type', 'status'], name='background__check_t_a48917_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundcheck',
            index=models.Index(fields=['provider_key', 'external_reference'], name='background__provide_6beda6_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundcheckevent',
            index=models.Index(fields=['background_check', 'event_type'], name='background__backgro_1d6ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundcheckevent',
            index=models.Index(fields=['created_at'], name='background__created_e9e3b5_idx'),
        ),
    ]
