# Generated by Django 5.2.11 on 2026-05-09 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_checks', '0002_cross_schema_fk_no_db_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheckWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(db_index=True, max_length=50)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('dead_letter', 'Dead Letter')], db_index=True, default='processed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('background_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='background_checks.backgroundcheck')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_key', 'external_reference'], name='background__provide_9c3ee8_idx'), models.Index(fields=['status', 'received_at'], name='background__status_a170df_idx')],
            },
        ),
    ]
