# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "name"], name="tenants_org_is_acti_c2ed40_idx"
            ),
        ),
    ]
