# Generated by Django 6.0.2 on 2026-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_organization_tenants_org_is_acti_c2ed40_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="tier",
            field=models.CharField(
                choices=[
                    ("starter", "Starter — free"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
    ]
