# Generated by Django 6.0.2 on 2026-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_organization_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="tier",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
    ]
