# Generated by Django 5.2.11 on 2026-03-05 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('executive', 'Executive'), ('legislative', 'Legislative'), ('judicial', 'Judicial'), ('independent', 'Independent Body'), ('local', 'Local Government')], db_index=True, max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('appointment_authority', models.CharField(max_length=200)),
                ('confirmation_required', models.BooleanField(default=False)),
                ('constitutional_basis', models.TextField(blank=True)),
                ('term_length_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_qualifications', models.TextField(blank=True)),
                ('is_vacant', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_positions', to='personnel.personnelrecord')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_positions', to='rubrics.vettingrubric')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['branch', 'institution'], name='positions_g_branch_0103d9_idx'), models.Index(fields=['is_public', 'is_vacant'], name='positions_g_is_publ_695231_idx')],
            },
        ),
    ]
