# Generated by Django 5.2.7 on 2026-03-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('personnel', '0002_personnelrecord_organization_and_more'),
        ('positions', '0001_initial'),
        ('rubrics', '0002_vetting_decision_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentposition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_positions', to='tenants.organization'),
        ),
        migrations.AddIndex(
            model_name='governmentposition',
            index=models.Index(fields=['organization', 'branch'], name='positions_g_organiz_8f1937_idx'),
        ),
    ]
