# Generated by Django 6.0.2 on 2026-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0002_governmentposition_organization_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="governmentposition",
            name="positions_g_organiz_8f1937_idx",
        ),
        migrations.RemoveField(
            model_name="governmentposition",
            name="organization",
        ),
    ]
