# Generated by Django 5.2.8 on 2025-12-05 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsistencyCheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("overall_consistent", models.BooleanField()),
                ("overall_score", models.FloatField()),
                ("name_consistency", models.JSONField(default=dict)),
                ("date_consistency", models.JSONField(default=dict)),
                ("entity_consistency", models.JSONField(default=dict)),
                ("recommendation", models.CharField(max_length=20)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consistency_result",
                        to="applications.vettingcase",
                    ),
                ),
            ],
            options={
                "db_table": "consistency_check_results",
            },
        ),
        migrations.CreateModel(
            name="FraudDetectionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_fraud", models.BooleanField()),
                ("fraud_probability", models.FloatField()),
                ("anomaly_score", models.FloatField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("PROCEED", "Proceed"),
                            ("MANUAL_REVIEW", "Manual Review"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feature_scores", models.JSONField(default=dict)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_result",
                        to="applications.vettingcase",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_detection_results",
            },
        ),
    ]
