# Generated by Django 5.2.11 on 2026-02-27 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_vettingcase_candidate_enrollment'),
        ('fraud', '0002_alter_consistencycheckresult_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfileCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_provided', models.BooleanField(default=False)),
                ('profiles_checked', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='HIGH', max_length=10)),
                ('recommendation', models.CharField(default='MANUAL_REVIEW', max_length=30)),
                ('automated_decision_allowed', models.BooleanField(default=False)),
                ('decision_constraints', models.JSONField(blank=True, default=list)),
                ('profiles', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile_result', to='applications.vettingcase')),
            ],
            options={
                'db_table': 'social_profile_check_results',
            },
        ),
    ]
